# ======
# Project Details
# ======
name: 'testing_project'
version: '1.0.0'
config-version: 2
profile: 'my-snowflake-db'
require-dbt-version: 0.17.2

# ======
# File Path Configs
# ======
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

# ======
# Snowflake Configs
# ======
quoting:
  database: true
  identifier: false
  schema: false
query-comment:
  comment: "{{ query_comment(node) }}"
  append: true




# ==================
# Model Configs
# ==================
models:
  +pre-hook:
    - "{{ logging.log_model_start_event() }}"
  +post-hook:
    - "{{ logging.log_model_end_event() }}"

  # ------------------
  # Logging Package https://hub.getdbt.com/fishtown-analytics/logging/latest/
  # ------------------
  logging:
    +schema: meta
    +post-hook:
      - "grant select on {{this}} to role reporter"

  # ------------------
  # Snowflake Spend Package https://gitlab.com/gitlab-data/snowflake_spend
  # ------------------
  snowflake_spend:
    +materialized: table
    xf:
      +schema: analytics



  testing_project:
      staging:
          materialized: view
          schema: testing
