my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ${{ secrets.DBT_PROFILE_SNOWFLAKE_ACCOUNT }}

      # User/password auth
      user: ${{ secrets.DBT_PROFILE_USER }}
      password: ${{ secrets.DBT_PROFILE_PASSWORD }}

      role: ${{ secrets.DBT_PROFILE_ROLE }}
      database: ${{ secrets.DBT_PROFILE_DB }}
      warehouse: ${{ secrets.DBT_PROFILE_WH }}
      schema: ${{ secrets.DBT_PROFILE_TESTING_SCHEMA }}
      threads: 1
      client_session_keep_alive: False