version: 2

sources:
  - name: Adventureworks
    database: ADVENTUREWORKS_DB
    schema: HUMANRESOURCES
    description: This is the source data from advw. I've loaded csv files into an S3 bucket and used that to then stage the files to a snowflake database
    tables: 
      - name: department
        description: "This is the source table for department information. We are pulling this data from advw"
      - name: employee
      - name: jobcandidate
      - name: shift
      - name: employeedepartmenthistory
      - name: employeepayhistory
