name: dbt

on:
  push:
    branches:
      - master

jobs:
  dbt:
    name: dbt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1

      - name: Get github secrets
        env: 
          DBT_PROFILE_TARGET:            dev
          DBT_PROFILE_SNOWFLAKE_ACCOUNT: "{{ env_var('DBT_PROFILE_SNOWFLAKE_ACCOUNT') }}"
          DBT_PROFILE_USER:              "{{ env_var('DBT_PROFILE_USER') }}"
          DBT_PROFILE_PASSWORD:          "{{ env_var('DBT_PROFILE_PASSWORD') }}"
          DBT_PROFILE_ROLE:              "{{ env_var('DBT_PROFILE_ROLE') }}"
          DBT_PROFILE_DB:                "{{ env_var('DBT_PROFILE_DB') }}"
          DBT_PROFILE_WH:                "{{ env_var('DBT_PROFILE_WH') }}"

        with:
          python-version: "3.7.x"
      - run: pip3 install dbt
      - run: dbt --version
      
      - run: dbt deps --profiles-dir ./.ci_profiles
      - run: dbt run --profiles-dir ./.ci_profiles
      - run: dbt test --profiles-dir ./.ci_profiles




