name: dbt_master_merge

on:
  push:
    branches:
      - master

env: 
  DBT_PROFILE_TARGET:            prod
  DBT_PROFILE_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_PROFILE_SNOWFLAKE_ACCOUNT }}
  DBT_PROFILE_USER:              ${{ secrets.DBT_PROFILE_USER }}
  DBT_PROFILE_PASSWORD:          ${{ secrets.DBT_PROFILE_PASSWORD }}
  DBT_PROFILE_ROLE:              ${{ secrets.DBT_PROFILE_ROLE }}
  DBT_PROFILE_PROD_DB:                ${{ secrets.DBT_PROFILE_PROD_DB }}
  DBT_PROFILE_WH:                ${{ secrets.DBT_PROFILE_WH }}
  DBT_PROFILE_SCHEMA:            PROD


jobs:
  dbt:
    name: dbt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1

        with:
          python-version: "3.7.x"
      - run: python -m pip install --upgrade pip
      - run: pip3 install dbt
      - run: dbt --version
      
      - run: dbt deps --profiles-dir ./.ci_profiles
      - run: dbt seed --profiles-dir ./.ci_profiles
      - run: dbt run --profiles-dir ./.ci_profiles
      - run: dbt test --profiles-dir ./.ci_profiles




